### ISSUE TITLE
Bankkonto eröffnen

### ISSUE THREAD

**Issue by Libermentix** [FreieMaker/orga#2]
## Bankkonto eröffnen
Um als Verein Gelder sammeln zu können, u.a. um Spenden und Mitgliedsbeiträge sammeln zu können, brauchen wir ein Bankkonto

## Ziel
Zum 1.10.2019 das Bankkonto beantragt zu haben

## Todos

- [x] Vorstände (@JanThar, @Libermentix) unterschreiben MV von 2019 (ggf. mit Kopie Personalausweis) ->  [Wurde durch @JanThar  an Notarin weitergeleitet](https://github.com/FreieMaker/orga/blob/master/docs/20190828_Mitgliederversammlung.md) bzw. #1 
- [x] @JanThar organisiert Notartermin (Abstimmung mit @cemonds, Abstimmung mit Notar über Dauer, notwendige Dokumente, Answesende, etc)
- [x] Eintragung im Vereinsregister macht die Notarin 
- [x] @Libermentix Ruft Auszug ggf. im Vereinsregister (Amtsgericht Aachen VR 5605)
- [x] @JanThar organisiert Banktermin (in Abstimmung mit Christoph, Doodle für Vorstände falls Anwesenheit notwenig-> Onlinebanking ist zwingend erforderlich, 1 Karte reicht ggf. 2)

**Comment by Libermentix** [comment]
@JanThar damit wären wir hier durch oder?
