### ISSUE TITLE
Zugangsdaten zentral verwaltbar machen

### ISSUE THREAD

**Issue by Libermentix** [FreieMaker/orga#3]
## Projektname
Zugangsdaten sollen zentral zugänglich sein, so dass der Vorstand neuen und weiteren Mitgliedern Passwörter nicht in Text-Form zukommen lassen muss sondern über ein digitales System zur Verfügung stellen kann.

## Ziel
5.10. sollten wir die Passwörter zusammengetragen haben

## Todos
- [x] @JanThar  organisiert Github Admin Rechte für neue Vorstände
- [ ]  @JanThar organisiert Admin Rechte für Slack
- [ ]  @JanThar organisert Twitter, Facebook, (Instagram,) Github
- [ ]  @JanThar organisiert Passwortliste

**Comment by JanThar** [comment]
- Github: Dummyaccount für Verein um virtuellen Owner zu haben (Fail-safe-passwort)
- Slack: Gibt eventuell die option kostenloses Upgrade wegen gemeinnützigkeit zu bekommen
- Instagram existiert tatsächlich, aber nie genutzt (unklar wer das gemacht hat)
- Twitter: chris hat getestet, Problem: Telefonnnummer

**Comment by Libermentix** [comment]
@JanThar Dummyaccount halte ich für nicht unbedingt die beste Lösung, wenn wir neue Owner hinzufügen bzw ändern können. Ansonsten müssten wir immer dran denken die Passwörter zu aktualisieren. 

Ein Hinzufügen und Entfernen von Ownerrechten bspw auf einer MV käme einer feierlichen Staffelstabübergabe gleich und wir könnten es so ritualisieren. 

Opinions?
